version: '3'

networks:

  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

services:

  redis-cluster:
    image: redis:latest
    command: redis-cli -p 7001 --cluster create 10.0.0.11:7001 10.0.0.12:7002 10.0.0.13:7003 10.0.0.14:7004 10.0.0.15:7005 10.0.0.16:7006 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      redisnet:
        ipv4_address: 10.0.0.2

  redis-1:
    build: ./redis
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7001
    networks:
      redisnet:
        ipv4_address: 10.0.0.11
    ports:
      - 7001:6379

  redis-2:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7002
    networks:
      redisnet:
        ipv4_address: 10.0.0.12
    ports:
      - 7002:6379

  redis-3:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7003
    networks:
      redisnet:
        ipv4_address: 10.0.0.13
    ports:
      - 7003:6379

  redis-4:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7004
    networks:
      redisnet:
        ipv4_address: 10.0.0.14
    ports:
      - 7004:6379

  redis-5:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7005
    networks:
      redisnet:
        ipv4_address: 10.0.0.15
    ports:
      - 7005:6379

  redis-6:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7006
    networks:
      redisnet:
        ipv4_address: 10.0.0.16
    ports:
      - 7006:6379